import React, { useState } from 'react';
import { calculateOverallRisk, getRecommendations } from '../logic/SmartRiskEngine';

import './StepDashboard.css';

/**
 * PUBLIC_INTERFACE
 * StepDashboard
 * Animated, tabbed dashboard with animated scorecard, micro-interactions, glassmorphism/neumorphism,
 * responsive layout, and stubs for download/email/share.
 */

/** Simple Toast component for demo CTA feedback */
function DemoToast({ message, onClose }) {
  React.useEffect(() => {
    if (!message) return;
    const timer = setTimeout(onClose, 2000);
    return () => clearTimeout(timer);
  }, [message]);
  if (!message) return null;
  return (
    <div
      className="dashboard-toast"
      style={{
        position: "fixed",
        bottom: 34,
        left: "50%",
        transform: "translateX(-50%)",
        background:
          "linear-gradient(92deg, var(--primary,#2563eb) 70%, var(--accent,#fbbf24) 130%)",
        color: "#fff",
        fontWeight: 600,
        fontSize: 17,
        borderRadius: 12,
        boxShadow: "0 2.5px 24px #2563eb33, 0 1.5px 5px #fff2",
        padding: "11px 34px",
        zIndex: 3333,
        opacity: 0.98,
        pointerEvents: "none",
      }}
      role="status"
      aria-live="polite"
    >
      {message}
    </div>
  );
}
import { saveReport } from "../logic/UserReportStore";

// PUBLIC_INTERFACE
function ScoreCard({ 
  quizScore, 
  contractRisk, 
  overallScore, 
  overallGrade, 
  showToast, 
  quizRisk, 
  contractFlags, 
  contractRecs, 
  summary, 
  recommendations 
}) {
  // Animate main score (on mount & score change).
  const [animatedScore, setAnimatedScore] = useState(0);
  React.useEffect(() => {
    let raf;
    const duration = 900;
    const start = 0;
    const end = overallScore;
    const update = (timestamp, startTime) => {
      const elapsed = Math.min(duration, timestamp - startTime);
      const value = Math.round(start + (end - start) * (elapsed / duration));
      setAnimatedScore(value);
      if (elapsed < duration) {
        raf = requestAnimationFrame(ts => update(ts, startTime));
      } else {
        setAnimatedScore(end);
      }
    };
    const startTime = performance.now();
    raf = requestAnimationFrame(ts => update(ts, startTime));
    return () => raf && cancelAnimationFrame(raf);
  }, [overallScore]);

  // Create a simple .txt report summarizing the dashboard results
  function getTextReport() {
    // Quiz section
    let text = '';
    text += "==== CyberLegal Insight Report ====\n";
    text += `Quiz Score: ${quizScore}/100 (${quizRisk || "N/A"})\n`;
    text += `Contract Safety Score: ${contractRisk}/100\n`;
    text += `Overall Risk: ${summary?.riskScore || "-"} /100 (${summary?.riskGrade || "-"})\n\n`;
    text += "Key Contract Findings:\n";
    if (Array.isArray(contractFlags) && contractFlags.length) {
      contractFlags.forEach((flag, idx) => {
        text += `  - ${flag}\n`;
      });
    } else {
      text += "  None detected.\n";
    }
    text += "\nSystem Recommendations:\n";
    if (Array.isArray(recommendations)) {
      recommendations.forEach((rec, idx) => {
        text += `  - ${rec}\n`;
      });
    }
    if (Array.isArray(contractRecs) && contractRecs.length) {
      text += "\nLegal Tips:\n";
      contractRecs.forEach((rec, i) => {
        text += `  - ${rec}\n`;
      });
    }
    return text + "\nGenerated by CyberLegal Insight Hub (https://cyberlegal.kavia.ai)\n";
  }

  // PUBLIC_INTERFACE
  // Download button handler: generate report as a .txt and trigger browser download
  const handleDownload = () => {
    try {
      const text = getTextReport();
      const blob = new Blob([text], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "cyberlegal-insight-report.txt";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 2222);
      showToast("Report downloaded!");
    } catch (e) {
      showToast("Failed to download report.");
    }
  };

  // PUBLIC_INTERFACE
  // Share handler: build a summary string, copy to clipboard, show toast
  const handleShare = async () => {
    const summaryStr = [
      "CyberLegal Insight Brief:",
      `Quiz: ${quizScore}/100 (${quizRisk || "-"})`,
      `Contract: ${contractRisk}/100`,
      `Overall: ${summary?.riskScore || "-"} /100 (${summary?.riskGrade || "-"})`,
      "Key Recommendation:",
      recommendations && recommendations[0] ? `- ${recommendations[0]}` : "",
      "(Full report generated at https://cyberlegal.kavia.ai)"
    ].filter(Boolean).join('\n');
    try {
      if (navigator.clipboard) {
        await navigator.clipboard.writeText(summaryStr);
        showToast("Summary copied to clipboard!");
      } else {
        // fallback approach (not recommended, but basic legacy support)
        const t = document.createElement("textarea");
        t.value = summaryStr;
        document.body.appendChild(t);
        t.select();
        document.execCommand("copy");
        document.body.removeChild(t);
        showToast("Summary copied!");
      }
    } catch (e) {
      showToast("Copy failed.");
    }
  };

  // Email can remain a stub or be omitted here as not required in the task
  const handleEmail = () => {
    showToast("Email report: Feature coming soon!");
  };

  return (
    <div className="glass-card neumorph-shadow dashboard-scorecard">
      <div className="dashboard-score-smalls">
        <div>
          <span className="score-label">Quiz</span>
          <span className="score-num">{quizScore}</span>
        </div>
        <div>
          <span className="score-label">Contract</span>
          <span className="score-num">{contractRisk}</span>
        </div>
      </div>
      <div className="score-main-anim" aria-label={`Overall Score: ${animatedScore}`}>
        <span className="score-big">{animatedScore}</span>
        <span className="score-grade">/100</span>
        <span className="score-tag">{overallGrade}</span>
      </div>
      <div className="score-cta-btns">
        <button className="dashboard-action-btn" title="Download report as TXT" onClick={handleDownload}>
          <span role="img" aria-label="download">⬇️</span>
        </button>
        <button className="dashboard-action-btn" title="Email report" onClick={handleEmail}>
          <span role="img" aria-label="email">✉️</span>
        </button>
        <button className="dashboard-action-btn" title="Share dashboard" onClick={handleShare}>
          <span role="img" aria-label="share">🔗</span>
        </button>
      </div>
    </div>
  );
}

/**
 * Enhanced: All dashboard tab content is generated dynamically as per quiz and contract state,
 * using fresh contextual logic. Risk-priority labels/explanations are included for actionable guidance.
 */

// PUBLIC_INTERFACE
function TipsTab({ recommendations, quizRisk, contractFlags, contractRecs }) {
  // Compose actionable, contextual, and risk-prioritized tips
  const hasContractFindings = Array.isArray(contractFlags) && contractFlags.some(flag => flag && !/no critical/i.test(flag));
  const adviceList = [];
  // Quiz risk label
  if (quizRisk && quizRisk !== "-") {
    adviceList.push(
      <li key="quizrisklabel">
        <b>Quiz Risk Level:</b> <span style={{color: quizRisk === 'Severe' ? "#b82727" : quizRisk === 'High' ? "#e87a41" : "#2563eb"}}>{quizRisk}</span>
        {quizRisk === "Severe" && (
          <span style={{color:"#b82727", fontWeight:500, marginLeft:8}}>❗ Immediate improvement needed.</span>
        )}
        {quizRisk === "High" && (
          <span style={{color:"#e87a41", fontWeight:500, marginLeft:8}}>⚠️ Review weak areas soon.</span>
        )}
      </li>
    );
  }
  // System recommendations (from engine)
  for (let i = 0; i < recommendations.length; ++i) {
    adviceList.push(
      <li key={"mainrec"+i}>{recommendations[i]}</li>
    );
  }
  // Contract findings/tips
  if (hasContractFindings && Array.isArray(contractFlags)) {
    contractFlags.forEach((flag, i) => {
      adviceList.push(
        <li key={"flag"+i}><b>Contract Issue:</b> {flag}</li>
      );
    });
  }
  if (hasContractFindings && Array.isArray(contractRecs)) {
    contractRecs.forEach((rec, i) => {
      adviceList.push(
        <li key={"recs"+i}><b>Legal Tip:</b> {rec}</li>
      );
    });
  }
  // Fallback for full safety
  if (!adviceList.length) adviceList.push(<li key="none">No additional recommendations. You're in good shape!</li>);
  return (
    <div className="dashboard-tab">
      <h4 style={{marginTop:0,marginBottom:6}}>Smart Recommendations</h4>
      <ul>
        {adviceList}
      </ul>
    </div>
  );
}

// PUBLIC_INTERFACE
function Checklist({ items, contractFlags }) {
  // Compose an actionable checklist, adding contract flags as top priority, labeled by risk
  const checklistItems = [];
  if (
    Array.isArray(contractFlags) && contractFlags.length > 0 &&
    !contractFlags.some(flag => /no critical/i.test(flag))
  ) {
    contractFlags.forEach((flag, i) =>
      checklistItems.push(`Review contract finding: ${flag}`)
    );
  }
  checklistItems.push(...items);
  // Dedup and render
  const unique = Array.from(new Set(checklistItems));
  return (
    <div className="dashboard-tab">
      <h4 style={{marginTop:0,marginBottom:6}}>Quick Checklist</h4>
      <ol className="dashboard-checklist">
        {unique.map((item, idx) =>
          <li key={idx}>
            <span className="checklist-bullet" aria-label="check" role="img">✅</span>
            {item}
          </li>
        )}
      </ol>
    </div>
  );
}

// PUBLIC_INTERFACE
function ActionPlan({ actionItems, overallGrade, quizRisk, contractFlags }) {
  // Start with core plan, inject urgent/priority steps based on risk and contract findings
  let plan = [];
  if (
    Array.isArray(contractFlags) && contractFlags.length > 0 &&
    !contractFlags.some(flag => /no critical/i.test(flag))
  ) {
    contractFlags.forEach(flag =>
      plan.push(`URGENT: Address contract finding: ${flag}`)
    );
  }
  if (quizRisk === "Severe" || quizRisk === "High") {
    plan.push("URGENT: Take phishing/cyber training ASAP");
  }
  if (overallGrade === "Severe" && !plan.includes("URGENT: Schedule compliance/legal audit")) {
    plan.push("URGENT: Schedule compliance/legal audit");
  } else if (overallGrade === "High" && !plan.includes("Schedule compliance review")) {
    plan.push("Schedule compliance review");
  }
  plan.push(...actionItems);
  plan = Array.from(new Set(plan));
  return (
    <div className="dashboard-tab">
      <h4 style={{marginTop:0,marginBottom:6}}>Action Plan</h4>
      <ul>
        {plan.map((act, idx) =>
          <li key={idx}>
            <span className="actionplan-dot" style={{
              filter: idx === 0 ? "brightness(1.12) saturate(1.18)" : "",
              marginRight:9
            }} />
            {act}
          </li>
        )}
      </ul>
    </div>
  );
}

/*
 * MAIN DASHBOARD COMPONENT
 * PUBLIC_INTERFACE
 * Aggregates and displays quiz and contract analysis results in an interactive tabbed dashboard.
 * Populates actionable content in all result tabs based on user data.
 */


function StepDashboard({
  goToNextStep,
  goToPrevStep,
  appData,
  quizScore,
  quizRisk,
  quizResults,
  contractRisk,
  contractFlags,
  contractRecs,
  contractUploaded,
  user, // <-- Accept user prop for report saving
}) {
  // Toast state for demo CTA feedback
  const [toastMsg, setToastMsg] = useState("");
  const showToast = (message) => {
    setToastMsg(message);
  };

  // Save a completed report automatically when data changes (only once per mounting for this user/data)
  React.useEffect(() => {
    if (!user) return;
    // Compose report data: essential summary + relevant state
    const report = {
      type: "riskAssessment",
      quizScore: mergedQuizScore,
      contractRisk: mergedContractRisk,
      overall: summary,
      quizRisk: mergedQuizRisk,
      contractFlags: mergedContractFlags,
      contractRecs: mergedContractRecs,
      recommendations,
      timestamp: Date.now(),
      quizResults: mergedQuizResults,
      contractUploaded,
    };
    // Save report (avoid duplicate saves by using a flag—report unique per data/user)
    // We'll save only if not latest, or if there are new results since last save
    // This is simple to avoid duplicate entries if the dashboard is re-mounted with different data
    let lastKey = null;
    try {
      lastKey = window.sessionStorage.getItem("cyberlegalLastReportKey");
    } catch {}
    const newKey = user.username + "|" + summary.riskScore + "|" + Date.now();
    if (lastKey !== newKey) {
      saveReport(user, report);
      try {
        window.sessionStorage.setItem("cyberlegalLastReportKey", newKey);
      } catch {}
    }
  // Only attempt to save when data changes, or on first load
  // eslint-disable-next-line
  }, [
    user && user.username,
    mergedQuizScore,
    mergedContractRisk,
    mergedQuizRisk,
    mergedQuizResults && JSON.stringify(mergedQuizResults),
    mergedContractFlags && JSON.stringify(mergedContractFlags),
    mergedContractRecs && JSON.stringify(mergedContractRecs),
    summary && summary.riskScore,
    recommendations && recommendations[0], // at least, catch overall rec
    contractUploaded,
  ]);

  // Data flow: prefer explicit state from props, else fallback to appData, else demo values
  const mergedQuizScore =
    quizScore ??
    appData?.quizScore ??
    78;
  const mergedContractRisk =
    contractRisk ??
    appData?.contractRisk ??
    63;

  const mergedQuizRisk =
    quizRisk ??
    appData?.quizRisk ??
    "-";
  const mergedQuizResults =
    quizResults ??
    appData?.quizResults ??
    undefined;

  const mergedContractFlags =
    contractFlags ??
    appData?.contractFlags ??
    [];
  const mergedContractRecs =
    contractRecs ??
    appData?.contractRecs ??
    [];

  // Overall/summary risk analysis
  const summary = calculateOverallRisk({
    quizScore: mergedQuizScore,
    contractRisk: mergedContractRisk
  });
  const recommendations = getRecommendations(summary.riskGrade);

  // Assemble checklist and actions with real/derived data
  const checklist = [
    ...recommendations.map(r => r.replace(/[.!?]$/, '')),
    "Update passwords across key accounts",
    "Enable two-factor authentication",
    "Schedule yearly contract review"
  ];
  const actionPlan = [
    "Download full results as PDF",
    "Forward report to legal or IT advisor",
    "Retake quiz in 90 days"
  ];

  // --- Quiz insights with detailed per-question feedback ---
  // We'll use the quiz questions (with explanations) for insights display.
  let QUIZ_QUESTIONS = undefined;
  try {
    // Dynamically require or import the quiz questions.
    // We'll use a dummy-local import like below (if available).
    QUIZ_QUESTIONS = require('../steps/StepCyberQuiz').default?.QUIZ_QUESTIONS ||
                     require('../steps/StepCyberQuiz').QUIZ_QUESTIONS ||
                     undefined;
  } catch (e) {
    // fallback: we'll redeclare here if bundler blocks require()
    QUIZ_QUESTIONS = [
      {
        id: 'q1',
        question: "You receive an email from your 'bank' asking to click a link and verify your account. What should you do?",
        options: [
          "Click the link and enter your credentials immediately.",
          "Delete the email without responding.",
          "Verify the sender's email, contact the bank directly, and avoid clicking suspicious links.",
          "Forward the email to friends as a precaution.",
        ],
        correct: 2,
        explanation:
          "Never click on email links from unknown or suspicious senders. Always independently verify such requests by contacting the bank using official contact info. This prevents phishing attacks."
      },
      {
        id: 'q2',
        question: "What is the MOST secure way to store your work passwords?",
        options: [
          "Write them in a notebook you keep in your desk drawer.",
          "Save them in a secure, encrypted password manager.",
          "Email them to yourself so you don't forget.",
          "Reuse the same simple password everywhere for convenience.",
        ],
        correct: 1,
        explanation:
          "Use a reputable password manager to create and store unique, complex passwords for all your accounts. Never reuse passwords or write them down in insecure locations."
      },
      {
        id: 'q3',
        question: "A colleague asks for access to confidential files. The request comes via text message. What should you do?",
        options: [
          "Share the files, since you know the colleague.",
          "Ignore the request.",
          "Call or verify the request through an official company channel, and follow your organization's data policy.",
          "Send the files only after your manager approves in writing.",
        ],
        correct: 2,
        explanation:
          "Always verify sensitive requests using official, secure channels—even if the requester is familiar. This prevents social engineering and potential data leaks."
      },
      {
        id: 'q4',
        question: "Which of these is a sign of a potentially unsafe website?",
        options: [
          "The web address starts with 'https://' and shows a padlock.",
          "The site asks for personal data and has spelling errors, odd pop-ups, or mismatched URL.",
          "It loads very quickly and has a modern design.",
          "There is a privacy policy linked at the bottom.",
        ],
        correct: 1,
        explanation:
          "Watch for spelling mistakes, unexpected data requests, mismatched URLs, and aggressive pop-ups—these may signal a phishing site. Always check for 'https://' but that's not a sole guarantee."
      },
      {
        id: 'q5',
        question: "Which of the following is LEGALLY acceptable digital behavior at work?",
        options: [
          "Sharing copyrighted media via company email to colleagues.",
          "Using only licensed and approved software for business purposes.",
          "Downloading torrents on the company network for convenience.",
          "Forwarding sensitive customer data to your personal email for work-from-home.",
        ],
        correct: 1,
        explanation:
          "Use only authorized, licensed software for business; unauthorized sharing of media or data can expose you and your employer to legal risk. Never send confidential data to personal accounts."
      },
    ];
  }

  // Now, generate detailed insight items for each answered quiz question:
  const quizInsight =
    mergedQuizResults && Array.isArray(mergedQuizResults) && QUIZ_QUESTIONS
      ? (
        <div>
          <h4 style={{marginTop:0,marginBottom:7}}>Quiz Insights</h4>
          <ul style={{paddingLeft: 0, listStyle: "none"}}>
            {mergedQuizResults.map((res, idx) => {
              const q = QUIZ_QUESTIONS.find(q => q.id === res.questionId) || QUIZ_QUESTIONS[idx] || {};
              const userAnswerIdx = (typeof res.userAnswer === "number") ? res.userAnswer : null;
              const userAnswerText = (userAnswerIdx !== null && Array.isArray(q.options) && q.options[userAnswerIdx])
                ? q.options[userAnswerIdx]
                : (userAnswerIdx === null ? "(no answer)" : "Unknown answer");
              const correctAnswerText = q.options && q.options[q.correct];
              return (
                <li key={res.questionId || idx} style={{
                  marginBottom:18,
                  borderLeft: res.isCorrect ? "4px solid #178f42" : "4px solid #b82727",
                  background: res.isCorrect ? "rgba(23,210,66,0.09)" : "rgba(184,39,39,0.08)",
                  borderRadius: 6,
                  padding: "10px 13px",
                  boxShadow: "0 1px 7px #2563eb09"
                }}>
                  <div style={{display:"flex",alignItems:"center",marginBottom:2}}>
                    <span style={{fontWeight: 700, fontSize:19, marginRight:10, color: res.isCorrect ? "#178f42" : "#b82727"}}>
                      {res.isCorrect ? "✔️" : "❌"}
                    </span>
                    <span style={{fontWeight:600, color:"#213", fontSize:15.7}}>Q{idx+1}:</span>
                    <span style={{fontWeight:600, color:"#234", marginLeft:4, fontSize:15.7}}>{q.question}</span>
                  </div>
                  <div style={{
                      marginTop:4,
                      marginBottom:3,
                      fontSize:14.3,
                      fontWeight:500,
                      color: res.isCorrect ? "#178f42" : "#b82727"
                  }}>
                    Your answer: <span style={{fontWeight:700}}>{userAnswerText}</span>
                  </div>
                  {!res.isCorrect && correctAnswerText && (
                    <div style={{
                      marginTop:0,
                      fontSize:13.7,
                      color:"#2563eb"
                    }}>
                      Correct answer: <span style={{fontWeight:600}}>{correctAnswerText}</span>
                    </div>
                  )}
                  <div style={{
                    marginTop:7,
                    fontSize:13.9,
                    color:"#476",
                    borderLeft: "3px solid #fbbf24",
                    paddingLeft: 9,
                    background:"rgba(251,191,36,0.07)",
                    borderRadius: 4,
                  }}>
                    <b>Tip:</b> {q.explanation}
                  </div>
                </li>
              );
            })}
          </ul>
          <div style={{marginTop:5, fontSize:14.5, color:'#678'}}>
            <b>Quiz Risk Level:</b> {mergedQuizRisk}
          </div>
        </div>
      )
      : (
        <div>
          <h4 style={{marginTop:0}}>Quiz Insights</h4>
          <div>No answer details available.</div>
        </div>
      );

  // Contract findings per actual user input
  const contractFindings = contractUploaded === false
    ? (
      <div>
        <h4 style={{marginTop:0}}>Contract Findings</h4>
        <div>No contract was uploaded for analysis.</div>
      </div>
    )
    : (
      <div>
        <h4 style={{marginTop:0,marginBottom:6}}>Contract Analysis</h4>
        <div><b>Red Flags:</b>
          <ul style={{marginBottom:2,paddingLeft:18}}>
            {(mergedContractFlags || []).length
              ? mergedContractFlags.map((flag, idx) => <li key={idx}>{flag}</li>)
              : <li>None found</li>
            }
          </ul>
        </div>
        <div><b>Recommendations:</b>
          <ul style={{marginBottom:2,paddingLeft:18}}>
            {(mergedContractRecs || []).length
              ? mergedContractRecs.map((rec, idx) => <li key={idx}>{rec}</li>)
              : <li>No recommendations provided.</li>
            }
          </ul>
        </div>
      </div>
    );

  // Compose all dashboard tabs
  const TABS = [
    {
      label: "Summary",
      icon: "📊",
      content: (
        <div>
          <div className="glass-card dashboard-panel-card">
            <div>
              <b>Quiz Score:</b> {mergedQuizScore} / 100{" "}
              <span style={{ color: "#2563eb", marginLeft: 5, fontWeight: 600 }}>
                {mergedQuizRisk}
              </span>
            </div>
            <div>
              <b>Contract Safety Score:</b> {mergedContractRisk} / 100
            </div>
            <div style={{ fontSize: 18, margin: '10px 0 7px 0' }}>
              <b>Overall:</b> {summary.riskScore} / 100{" "}
              <span style={{ fontWeight: 600 }}>{summary.riskGrade}</span>
            </div>
            {quizInsight}
            <div style={{margin:"11px 0"}}>{contractFindings}</div>
          </div>
        </div>
      )
    },
    {
      label: "Quiz Insights",
      icon: "🧩",
      content: (<div className="glass-card dashboard-panel-card">{quizInsight}</div>)
    },
    {
      label: "Contract Findings",
      icon: "📑",
      content: (<div className="glass-card dashboard-panel-card">{contractFindings}</div>)
    },
    {
      label: "Tips",
      icon: "💡",
      content: <TipsTab
        recommendations={recommendations}
        quizRisk={mergedQuizRisk}
        contractFlags={mergedContractFlags}
        contractRecs={mergedContractRecs}
      />
    },
    {
      label: "Checklist",
      icon: "☑️",
      content: <Checklist
        items={checklist}
        contractFlags={mergedContractFlags}
      />
    },
    {
      label: "Action Plan",
      icon: "🚀",
      content: <ActionPlan
        actionItems={actionPlan}
        overallGrade={summary.riskGrade}
        quizRisk={mergedQuizRisk}
        contractFlags={mergedContractFlags}
      />
    }
  ];
  const [tab, setTab] = useState(0);

  // Animate fade-in for tab panel on change
  const [tabKey, setTabKey] = useState(0);
  React.useEffect(() => { setTabKey(tab + Math.random()); }, [tab]);

  return (
    <div className="step step-dashboard" style={{
      display: 'flex', flexDirection: 'column', alignItems: 'center'
    }}>
      <h2 style={{
        marginTop: 0, marginBottom: 22, fontWeight: 700, letterSpacing: "-0.5px"
      }}>
        Risk Assessment Results
      </h2>
      <ScoreCard
        quizScore={mergedQuizScore}
        contractRisk={mergedContractRisk}
        overallScore={summary.riskScore}
        overallGrade={summary.riskGrade}
        showToast={showToast}
        quizRisk={mergedQuizRisk}
        contractFlags={mergedContractFlags}
        contractRecs={mergedContractRecs}
        summary={summary}
        recommendations={recommendations}
      />
      <DemoToast message={toastMsg} onClose={() => setToastMsg("")} />
      <div className="dashboard-tabs-nav" role="tablist" aria-label="Dashboard Subsections">
        {TABS.map((t, i) =>
          <button
            key={t.label}
            className={`dashboard-tab-btn${tab === i ? " active" : ""}`}
            onClick={() => setTab(i)}
            type="button"
            aria-selected={tab === i}
            tabIndex={tab === i ? 0 : -1}
            role="tab"
            style={{ transitionDelay: `${i * 31}ms` }}
          >
            <span style={{ fontSize: 22, marginRight: 5 }}>{t.icon}</span> {t.label}
          </button>
        )}
      </div>
      <div className="dashboard-tabs-panel anim-fadein" key={tabKey}>
        {TABS[tab].content}
      </div>
      <div style={{
        marginTop: 30, display: 'flex', gap: 18, flexWrap: "wrap",
        justifyContent: "center"
      }}>
        <button className="btn" onClick={goToPrevStep}>Back</button>
        <button className="btn btn-large" onClick={goToNextStep}>Finish</button>
      </div>
    </div>
  );
}

// Simple style for the toast feedback (injected inline for demo)
// In a real app, move to StepDashboard.css
// Toast will pop down, then fade out
// Anim class handled by the component; just a quick transition for now.
export default StepDashboard;
