import React, { useEffect, useState } from "react";
import { getReports, getReportById } from "../logic/UserReportStore";
import HistoryTimeline from "./HistoryTimeline";

/**
 * PUBLIC_INTERFACE
 * ReportHistoryModal: Modal showing user's past report history.
 * - Fetches from localStorage (or guest session) according to user
 * - Lists all saved reports with actions: View, Download, Share, Delete
 * - Styled as modal matching app's visual theme
 * - Now includes interactive timeline and comparison panel
 */
function formatDate(dateString) {
  // Nice date, fallback for bad parse
  try {
    const d = new Date(dateString);
    return d.toLocaleString(undefined, {
      year: "numeric", month: "short", day: "numeric",
      hour: "2-digit", minute: "2-digit"
    });
  } catch {
    return dateString || "Unknown";
  }
}

function getTextReport(report) {
  if (!report) return "";
  let text = '';
  text += "==== CyberLegal Insight Report ====\n";
  text += `Quiz Score: ${report.quizScore}/100 (${report.quizRisk || "N/A"})\n`;
  text += `Contract Safety Score: ${report.contractRisk}/100\n`;
  text += `Overall Risk: ${report?.overall?.riskScore || "-"} /100 (${report?.overall?.riskGrade || "-"})\n\n`;
  text += "Key Contract Findings:\n";
  if (Array.isArray(report.contractFlags) && report.contractFlags.length) {
    report.contractFlags.forEach((flag) => {
      text += `  - ${flag}\n`;
    });
  } else {
    text += "  None detected.\n";
  }
  text += "\nSystem Recommendations:\n";
  if (Array.isArray(report.recommendations)) {
    report.recommendations.forEach((rec) => {
      text += `  - ${rec}\n`;
    });
  }
  if (Array.isArray(report.contractRecs) && report.contractRecs.length) {
    text += "\nLegal Tips:\n";
    report.contractRecs.forEach((rec) => {
      text += `  - ${rec}\n`;
    });
  }
  return text + "\nGenerated by CyberLegal Insight Hub (https://cyberlegal.kavia.ai)\n";
}

function summaryString(report) {
  if (!report) return "No summary available.";
  return [
    "CyberLegal Insight Brief:",
    `Quiz: ${report.quizScore}/100 (${report.quizRisk || "-"})`,
    `Contract: ${report.contractRisk}/100`,
    `Overall: ${report?.overall?.riskScore || "-"} /100 (${report?.overall?.riskGrade || "-"})`,
    "Key Recommendation:",
    report.recommendations && report.recommendations[0] ? `- ${report.recommendations[0]}` : "",
    "(Full report generated at https://cyberlegal.kavia.ai)"
  ].filter(Boolean).join('\n');
}

function ReportHistoryModal({ isOpen, onClose, user }) {
  const [reports, setReports] = useState([]);
  const [selectedReportId, setSelectedReportId] = useState(null);
  const [previewReport, setPreviewReport] = useState(null);
  const [toast, setToast] = useState("");
  const [compareIds, setCompareIds] = useState([]);

  // Always run, update report list depending on modal/user state
  useEffect(() => {
    if (isOpen && user) {
      const list = getReports(user);
      setReports(list);
    } else {
      setReports([]);
    }
  }, [isOpen, user]);

  // Always run, update preview report any time selectedReportId or user changes
  useEffect(() => {
    if (user && selectedReportId) {
      const report = getReportById(user, selectedReportId);
      setPreviewReport(report);
    } else {
      setPreviewReport(null);
    }
  }, [selectedReportId, user]);

  // New: Sync timeline compare selection
  useEffect(() => {
    if (compareIds.length === 1 && user) {
      const report = getReportById(user, compareIds[0]);
      setPreviewReport(report);
      setSelectedReportId(compareIds[0]);
    } else if (compareIds.length === 2 && user) {
      setPreviewReport(null);
      setSelectedReportId(null);
    } else if (compareIds.length === 0) {
      setPreviewReport(null);
      setSelectedReportId(null);
    }
  }, [compareIds, user]);

  // Toast timeout effect (always called)
  useEffect(() => {
    if (!toast) return;
    const timer = setTimeout(() => setToast(""), 1600);
    return () => clearTimeout(timer);
  }, [toast]);

  if (!isOpen) return null;

  // Download a report (txt):
  function handleDownload(report) {
    try {
      const text = getTextReport(report);
      const blob = new Blob([text], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "cyberlegal-insight-report.txt";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 2222);
      setToast("Report downloaded!");
    } catch {
      setToast("Failed to download report.");
    }
  }

  // Share summary to clipboard
  async function handleShare(report) {
    const summaryStr = summaryString(report);
    try {
      if (navigator.clipboard) {
        await navigator.clipboard.writeText(summaryStr);
        setToast("Summary copied to clipboard!");
      } else {
        const t = document.createElement("textarea");
        t.value = summaryStr;
        document.body.appendChild(t);
        t.select();
        document.execCommand("copy");
        document.body.removeChild(t);
        setToast("Summary copied!");
      }
    } catch {
      setToast("Copy failed.");
    }
  }

  return (
    <div
      className="report-history-modal-backdrop"
      style={{
        position: "fixed",
        top: 0, left: 0, right: 0, bottom: 0,
        zIndex: 1999,
        background: "rgba(38,38,50,0.22)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center"
      }}
      tabIndex={-1}
      aria-modal="true"
      role="dialog"
    >
      <div
        className="glass-card"
        style={{
          minWidth: 320, maxWidth: 530, width: "99vw",
          padding: "2rem 1.35rem 1.5rem 1.35rem",
          boxShadow: "0 10px 44px 0 #2563eb19",
          borderRadius: 20,
          position: "relative",
          maxHeight: "85vh",
          overflow: "auto"
        }}
      >
        <button
          style={{
            background: "none",
            border: "none",
            position: "absolute",
            top: 10, right: 13,
            fontSize: 23,
            color: "var(--text-secondary)",
            cursor: "pointer"
          }}
          aria-label="Close"
          onClick={onClose}
        >✖</button>
        <h3 style={{
          margin: "4px 0 13px 0",
          fontWeight: 800,
          color: "var(--primary,#2563eb)",
          fontSize: "1.35rem"
        }}>
          <span role="img" aria-label="history" style={{marginRight:7,fontSize:23}}>📑</span>
          Saved Reports & History
        </h3>
        {toast && (
          <div
            style={{
              background: "linear-gradient(93deg,var(--primary,#2563eb),var(--accent,#fbbf24))",
              color: "#fff",
              fontWeight: 600,
              fontSize: 15,
              borderRadius: 7,
              boxShadow: "0 2.5px 10px #2563eb33",
              padding: "5px 19px",
              position: "fixed",
              top: 20,
              left: "50%",
              transform: "translateX(-50%)",
              zIndex: 2001,
              opacity: 0.99
            }}
            role="status" aria-live="polite"
          >{toast}</div>
        )}
        {/* INTERACTIVE TIMELINE */}
        <HistoryTimeline
          reports={reports}
          onCompare={setCompareIds}
          defaultCompareIds={compareIds}
        />
        {compareIds.length === 2 && (
          <ReportComparisonPanel
            reportA={reports.find(r => r.id === compareIds[0])}
            reportB={reports.find(r => r.id === compareIds[1])}
          />
        )}
        {reports && reports.length ? (
          <ul style={{ padding: 0, listStyle: "none", marginBottom: 0 }}>
            {reports.map((r, idx) => (
              <li
                key={r.id || idx}
                style={{
                  background: "rgba(251,191,36,0.10)",
                  marginBottom: 13,
                  padding: "10px 7px 9px 12px",
                  borderRadius: 9,
                  position: "relative",
                  display: "flex",
                  flexDirection: "column"
                }}
              >
                <div style={{display:"flex", alignItems:"center", justifyContent:"space-between"}}>
                  <div>
                    <b>Report:</b> <span style={{color:"var(--primary,#2563eb)", fontWeight:600}}>#{reports.length-idx}</span>
                    <span style={{marginLeft:6,color:"var(--text-secondary)",fontSize:13}}>
                      {formatDate(r.date || r.timestamp)}
                    </span>
                    {r.overall?.riskGrade && (
                      <span style={{
                        background: "rgba(37,99,235,0.09)",
                        color: "var(--kavia-orange,#E87A41)",
                        fontWeight:600,
                        borderRadius: 7,
                        padding: "2px 8px",
                        fontSize: 13,
                        marginLeft: 8
                      }}>
                        {r.overall.riskGrade}
                      </span>
                    )}
                  </div>
                  <div style={{display:"flex",gap:7}}>
                    <button
                      className="dashboard-action-btn"
                      title="View details"
                      style={{fontSize:15,padding:"3px 8px"}}
                      onClick={() => { setSelectedReportId(r.id); setCompareIds([]); }}
                    >👁️</button>
                    <button
                      className="dashboard-action-btn"
                      title="Download report"
                      style={{fontSize:15,padding:"3px 8px"}}
                      onClick={() => handleDownload(r)}
                    >⬇️</button>
                    <button
                      className="dashboard-action-btn"
                      title="Share summary"
                      style={{fontSize:15,padding:"3px 8px"}}
                      onClick={() => handleShare(r)}
                    >🔗</button>
                  </div>
                </div>
                {/* Minimal result summary */}
                <div style={{ marginTop: 4, color: "var(--text-secondary)", fontSize: 13.8 }}>
                  Quiz: <b>{r.quizScore}</b> / 100,&nbsp;
                  Contract: <b>{r.contractRisk}</b> / 100,&nbsp;
                  Overall: <b>{r.overall?.riskScore || "-" }</b> / 100&nbsp;
                  <span style={{fontWeight:600}}>{r.overall?.riskGrade || ""}</span>
                </div>
              </li>
            ))}
          </ul>
        ) : (
          <div style={{
            color: "var(--text-secondary)",
            textAlign: "center",
            fontWeight: 500,
            minHeight: 80,
            display:"flex",
            flexDirection:"column",
            alignItems:"center",
            justifyContent:"center"
          }}>
            <span style={{fontSize:33,opacity:0.7,marginBottom:7}}>🗂️</span>
            No saved reports yet.
          </div>
        )}
        {previewReport && (
          <div
            className="glass-card"
            style={{
              position: "fixed",
              zIndex: 2005,
              left: "50%", top: "50%",
              transform: "translate(-50%, -50%)",
              minWidth:300,
              maxWidth:560,
              width: "97vw",
              boxShadow: "0 3px 44px 0 #e87a4118",
              borderRadius: 21,
              background: "var(--glass-bg,#fff)",
              padding:"2rem 1.6rem 1.2rem 1.6rem",
            }}
          >
            <button
              style={{
                background: "none",
                border: "none",
                position: "absolute",
                top: 12, right: 15,
                fontSize: 23,
                color: "var(--text-secondary)",
                cursor: "pointer"
              }}
              aria-label="Close"
              onClick={() => setSelectedReportId(null)}
            >✖</button>
            <h4 style={{
              fontWeight:800,marginTop:0,color:"var(--primary)",fontSize:"1.19rem"
            }}>Report Details</h4>
            <pre style={{
              whiteSpace:"pre-wrap",
              background:"rgba(251,191,36,0.09)",
              padding:"9px 11px",
              borderRadius: 8,
              fontSize: 14,
              marginBottom:8,
              color:"var(--kavia-dark,#242)"
            }}>{getTextReport(previewReport)}</pre>
            <div style={{display:"flex",gap:13,justifyContent:"flex-end"}}>
              <button
                className="dashboard-action-btn"
                onClick={() => {
                  handleDownload(previewReport);
                  setSelectedReportId(null);
                }}
                title="Download"
                style={{fontSize:14,padding:"3.5px 10px"}}
              >⬇️ Download</button>
              <button
                className="dashboard-action-btn"
                onClick={() => {
                  handleShare(previewReport);
                  setSelectedReportId(null);
                }}
                title="Share"
                style={{fontSize:14,padding:"3.5px 10px"}}
              >🔗 Share</button>
              <button
                className="dashboard-action-btn"
                onClick={() => setSelectedReportId(null)}
                style={{fontSize:14,padding:"3.5px 10px"}}
              >Close</button>
            </div>
          </div>
        )}
      </div>
      <style>{`
        .report-history-modal-backdrop {
          animation: fadein-report-history 0.22s cubic-bezier(.42,0,.58,1) both;
        }
        @keyframes fadein-report-history {
          from { opacity:0; }
          to { opacity:1; }
        }
      `}</style>
    </div>
  );
}

/**
 * Panel to show side-by-side comparison of two reports
 * Props: reportA, reportB (both report objects)
 */
function ReportComparisonPanel({ reportA, reportB }) {
  if (!reportA || !reportB) return null;

  // For display order: show newest on left (lower index is newer in timeline)
  const isAnewer = (new Date(reportA.date || reportA.timestamp)) > (new Date(reportB.date || reportB.timestamp));
  const left = isAnewer ? reportA : reportB;
  const right = isAnewer ? reportB : reportA;

  // Helper for diffs
  function highlightDiff(field, valA, valB) {
    if (valA === valB) return <span>{valA ?? "-"}</span>;
    return (
      <span>
        <span style={{ background: "#fbbf2480", borderRadius: 4, padding: "0 5px", fontWeight: 600 }}>{valA ?? "-"}</span>
        <span style={{ color: "#b82727", margin: "0 7px" }}>→</span>
        <span style={{ background: "#178f4255", borderRadius: 4, padding: "0 5px", fontWeight: 600 }}>{valB ?? "-"}</span>
      </span>
    );
  }

  // Key fields for compare
  const FIELDS = [
    ["Quiz Score", "quizScore"],
    ["Contract Risk", "contractRisk"],
    ["Overall Score", "overall.riskScore"],
    ["Risk Level", "overall.riskGrade"],
    ["Contract Findings", "contractFlags"],
    ["Contract Recs", "contractRecs"],
  ];

  function getField(r, key) {
    if (key.includes(".")) {
      const [k, sub] = key.split(".");
      return r[k]?.[sub];
    }
    return r[key];
  }
  function renderListDiff(a, b) {
    if (JSON.stringify(a) === JSON.stringify(b)) return <span>{Array.isArray(a)?a.join("; "):"-"}</span>;
    return (
      <span>
        <span style={{ background: "#fbbf2480", borderRadius: 4, padding: "0 4px", fontWeight: 600 }}>{Array.isArray(a)?a.join("; "):"-"}</span>
        <span style={{ color: "#b82727", margin: "0 7px" }}>→</span>
        <span style={{ background: "#178f4255", borderRadius: 4, padding: "0 4px", fontWeight: 600 }}>{Array.isArray(b)?b.join("; "):"-"}</span>
      </span>
    );
  }

  return (
    <div
      className="glass-card"
      style={{
        marginTop: 13,
        background: "rgba(37,99,235,0.07)",
        border: "1.5px solid var(--accent,#fbbf24)",
        borderRadius: 14,
        padding: "21px 13px",
        fontSize:15.1,
        fontWeight:500,
        boxShadow: "0 2.5px 12px #2563eb11",
      }}
    >
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
        <h4 style={{margin:"0 0 13px 4px",color:"var(--primary,#2563eb)",fontWeight:800,fontSize:"1.09rem"}}>
          Report Comparison
        </h4>
        <span style={{color:"var(--kavia-orange,#E87A41)",fontWeight:700,fontSize:13}}>
          #{left.id === reportA.id ? "A":"B"} vs #{right.id === reportB.id ? "B":"A"}
        </span>
      </div>
      <table style={{width:"100%",fontSize:14.2,borderCollapse:"collapse"}}>
        <thead>
          <tr>
            <th style={{textAlign:"left", paddingBottom:4, color:"var(--primary,#2563eb)", fontSize:13.5, fontWeight:700}}>Field</th>
            <th style={{color:"#222", paddingBottom:4}}>Report A</th>
            <th style={{color:"#222", paddingBottom:4}}>Report B</th>
          </tr>
        </thead>
        <tbody>
          {FIELDS.map(([label, key])=>(
            <tr key={key} style={{background:"rgba(251,191,36,0.08)"}}>
              <td style={{fontWeight:600,padding:"7px 5px 7px 0",minWidth: 105}}>{label}</td>
              <td style={{padding:"7px 7px"}}>{
                key.includes("contract") 
                  ? renderListDiff(getField(left, key), getField(right, key))
                  : highlightDiff(label, getField(left, key), getField(right, key))
              }</td>
              <td style={{padding:"7px 7px"}}>{
                key.includes("contract") 
                  ? renderListDiff(getField(right, key), getField(left, key))
                  : highlightDiff(label, getField(right, key), getField(left, key))
              }</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default ReportHistoryModal;
